export { Icon } from './Icon.js'
export type { IconProps } from './Icon.js'
export { ICON_FAMILIES, ICON_NAMES, ICON_PATHS, isIconName } from './registry.js'
export type { IconName } from './registry.js'
export { iconForIngredient, iconForRayon, normalizeLabel, rayonSlug } from './resolve.js'
export type { IngredientLike } from './resolve.js'
